import { prisma } from "@/lib/prisma";

async function seedScholarships() {
  const scholarships = [
    {
      title: "Global Excellence Scholarship",
      description: "Fully funded scholarship for high-achieving students from developing countries pursuing STEM degrees.",
      providerName: "International Education Foundation",
      amount: 50000,
      currency: "USD",
      fieldOfStduy: ["STEM", "Computer Science", "Engineering"],
      degreeLevel: "Bachelor",
      targetCountry: "USA",
      eligibleRegions: ["South Asia", "Southeast Asia", "Africa"],
      deadline: new Date("2026-06-30"),
      officialWebsite: "https://www.iedf.org/global-excellence",
      isFeatured: true,
      views: 1200,
    },
    {
      title: "Chevening Scholarship",
      description: "UK government funded scholarship for future leaders and influencers from around the world.",
      providerName: "British Council",
      amount: 30000,
      currency: "GBP",
      fieldOfStduy: ["Business", "Policy", "Social Sciences"],
      degreeLevel: "Master",
      targetCountry: "United Kingdom",
      eligibleRegions: ["Europe", "Asia", "Americas"],
      deadline: new Date("2026-11-06"),
      officialWebsite: "https://www.chevening.org",
      isFeatured: true,
      views: 2100,
    },
    {
      title: "Fulbright Scholarship",
      description: "Exchange program providing scholarships for international students to study in the United States.",
      providerName: "US State Department",
      amount: 45000,
      currency: "USD",
      fieldOfStduy: ["All fields"],
      degreeLevel: "Master",
      targetCountry: "USA",
      eligibleRegions: ["All regions"],
      deadline: new Date("2026-10-15"),
      officialWebsite: "https://www.fulbrightprogram.org",
      isFeatured: true,
      views: 3500,
    },
    {
      title: "Erasmus Mundus Scholarship",
      description: "European Commission scholarship for Master's students studying in European universities.",
      providerName: "European Commission",
      amount: 25000,
      currency: "EUR",
      fieldOfStduy: ["European Studies", "Engineering", "Environmental Science"],
      degreeLevel: "Master",
      targetCountry: "Multiple",
      eligibleRegions: ["Europe", "Asia", "Africa"],
      deadline: new Date("2026-08-20"),
      officialWebsite: "https://www.erasmusmundus.eu",
      isFeatured: false,
      views: 980,
    },
    {
      title: "DAAD Scholarships",
      description: "German Academic Exchange Service scholarships for international students studying in Germany.",
      providerName: "DAAD",
      amount: 934,
      currency: "EUR",
      fieldOfStduy: ["All fields"],
      degreeLevel: "Bachelor",
      targetCountry: "Germany",
      eligibleRegions: ["All regions"],
      deadline: new Date("2026-09-15"),
      officialWebsite: "https://www.daad.de",
      isFeatured: false,
      views: 1450,
    },
    {
      title: "Commonwealth Scholarship",
      description: "Scholarship for students from Commonwealth countries to study in Commonwealth universities.",
      providerName: "Commonwealth Commission",
      amount: 35000,
      currency: "GBP",
      fieldOfStduy: ["Development", "Education", "Technology"],
      degreeLevel: "Master",
      targetCountry: "United Kingdom",
      eligibleRegions: ["Commonwealth countries"],
      deadline: new Date("2026-07-10"),
      officialWebsite: "https://www.acu.ac.uk/scholarships",
      isFeatured: false,
      views: 750,
    },
    {
      title: "Canada Government Scholarship",
      description: "Vanier Canada Graduate Scholarships for doctoral students at Canadian universities.",
      providerName: "Government of Canada",
      amount: 50000,
      currency: "CAD",
      fieldOfStduy: ["Research", "Innovation", "Science"],
      degreeLevel: "PhD",
      targetCountry: "Canada",
      eligibleRegions: ["All regions"],
      deadline: new Date("2026-05-30"),
      officialWebsite: "https://vanier.gc.ca",
      isFeatured: true,
      views: 1100,
    },
    {
      title: "China Government Scholarship",
      description: "Scholarship program for international students to study at universities in China.",
      providerName: "Ministry of Education, China",
      amount: 15000,
      currency: "USD",
      fieldOfStduy: ["All fields"],
      degreeLevel: "Bachelor",
      targetCountry: "China",
      eligibleRegions: ["Asia", "Africa", "Americas"],
      deadline: new Date("2026-04-30"),
      officialWebsite: "https://www.csc.edu.cn",
      isFeatured: false,
      views: 890,
    },
    {
      title: "Switzerland Excellence Scholarship",
      description: "Excellence Scholarships for foreign scholars and researchers at Swiss universities.",
      providerName: "Swiss Government",
      amount: 28000,
      currency: "CHF",
      fieldOfStduy: ["Research", "Science", "Mathematics"],
      degreeLevel: "PhD",
      targetCountry: "Switzerland",
      eligibleRegions: ["Europe", "North America"],
      deadline: new Date("2026-08-31"),
      officialWebsite: "https://www.sbfi.admin.ch",
      isFeatured: false,
      views: 620,
    },
    {
      title: "Japan MEXT Scholarship",
      description: "Ministry of Education, Culture, Sports, Science and Technology scholarship for international students.",
      providerName: "Japanese Government",
      amount: 20000,
      currency: "JPY",
      fieldOfStduy: ["All fields"],
      degreeLevel: "Master",
      targetCountry: "Japan",
      eligibleRegions: ["All regions"],
      deadline: new Date("2026-05-15"),
      officialWebsite: "https://www.mext.go.jp",
      isFeatured: false,
      views: 1300,
    },
    {
      title: "Australian Government Scholarship",
      description: "Australia Awards Scholarships for students from developing countries.",
      providerName: "Australian Government",
      amount: 40000,
      currency: "AUD",
      fieldOfStduy: ["Development", "Agriculture", "Health"],
      degreeLevel: "Master",
      targetCountry: "Australia",
      eligibleRegions: ["Asia", "Pacific", "Africa"],
      deadline: new Date("2026-06-15"),
      officialWebsite: "https://www.australiaawards.gov.au",
      isFeatured: true,
      views: 1680,
    },
    {
      title: "New Zealand Government Scholarship",
      description: "New Zealand Aid Programme scholarships for students from partner countries.",
      providerName: "New Zealand Government",
      amount: 35000,
      currency: "NZD",
      fieldOfStduy: ["Development", "Governance", "Education"],
      degreeLevel: "Master",
      targetCountry: "New Zealand",
      eligibleRegions: ["Pacific", "Asia", "Africa"],
      deadline: new Date("2026-07-31"),
      officialWebsite: "https://www.mfat.govt.nz",
      isFeatured: false,
      views: 540,
    },
    {
      title: "Netherlands Government Scholarship",
      description: "Orange Knowledge Programme (OKP) scholarships for professionals from developing countries.",
      providerName: "Netherlands Ministry of Foreign Affairs",
      amount: 22000,
      currency: "EUR",
      fieldOfStduy: ["Development", "Water Management", "Education"],
      degreeLevel: "Master",
      targetCountry: "Netherlands",
      eligibleRegions: ["Africa", "Asia", "Latin America"],
      deadline: new Date("2026-09-30"),
      officialWebsite: "https://www.nuffic.nl",
      isFeatured: false,
      views: 650,
    },
    {
      title: "Nordic Government Scholarship",
      description: "Scholarships for international students pursuing degrees at Nordic universities.",
      providerName: "Nordic Council of Ministers",
      amount: 30000,
      currency: "EUR",
      fieldOfStduy: ["Technology", "Sustainability", "Innovation"],
      degreeLevel: "Master",
      targetCountry: "Multiple",
      eligibleRegions: ["All regions"],
      deadline: new Date("2026-10-15"),
      officialWebsite: "https://www.norden.org",
      isFeatured: false,
      views: 720,
    },
    {
      title: "South Korea Global Korea Scholarship",
      description: "Government scholarship for international students at Korean universities.",
      providerName: "Korean Government",
      amount: 18000,
      currency: "KRW",
      fieldOfStduy: ["All fields"],
      degreeLevel: "Bachelor",
      targetCountry: "South Korea",
      eligibleRegions: ["All regions"],
      deadline: new Date("2026-06-01"),
      officialWebsite: "https://www.niied.go.kr",
      isFeatured: false,
      views: 950,
    },
  ];

  try {
    console.log(`Seeding ${scholarships.length} scholarships...`);
    
    for (const scholarship of scholarships) {
      await prisma.scholarship.create({
        data: scholarship,
      });
    }

    console.log(`Successfully seeded ${scholarships.length} scholarships!`);
  } catch (error) {
    console.error("Error seeding scholarships:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedScholarships()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
